export const INPUT_NAME_REG = 'INPUT_NAME_REG';
export const INPUT_SURNAME_REG = 'INPUT_SURNAME_REG';
export const INPUT_EMAIL_REG = 'INPUT_EMAIL_REG';
export const INPUT_PASSWORD_REG = 'INPUT_PASSWORD_REG';
export const RETYPE_PASSWORD = 'RETYPE_PASSWORD';
export const REGISTER = 'REGISTER';
export const HANDLE_CANCEL = 'HANDLE_CANCEL';
export const GET_REGISTER_STATUS = 'GET_REGISTER_STATUS';
